### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asdjklfgh** [S-H-Y-GitHub/RS#1]
How can I solve the problem?
 test
无法执行赋值，因为左侧的大小为 512×512，右侧的大小为 512×512×3。

出错 im2col (line 63)
        aPad(1:size(a,1),1:size(a,2)) = a;

出错 rs (line 11)
    cols = im2col(img, [8 8], 'distinct');  % 将8x8 的块转化为列

出错 test (line 9)
    [data(2,i),data(3,i),data(4,i),data(5,i)]=rs(newimg);

**Comment by shuaihuaiyi** [comment]
不用MATLAB好多年，无法提供帮助，自行查找资料解决一下吧
